site_name: Pydantic2
site_description: A powerful library for structured LLM responses with Pydantic models
site_author: Mark Olofsen
repo_url: https://github.com/markolofsen/pydantic2
repo_name: markolofsen/pydantic2

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  icon:
    logo: material/library
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Django Integration: examples/django-integration.md
  - About:
    - License: about/license.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markolofsen/pydantic2
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pydantic2/
    - icon: fontawesome/solid/globe
      link: https://unrealos.com
copyright: Copyright &copy; 2024 UnrealOS

